apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DSSP-TargetP-89
  annotations:
    github.com/project-slug: BackstageSSPPoC/DSSP-TargetP-89
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: DSSP-TargetP-89
    sonarqube.org/project-key: dssp-targetp-89
    jenkins.io/job-full-name: Backstage_SSP_PoC/DSSP-TargetP-89/main
    argocd/app-name: dssp-targetp-89-dev
    prometheus.io/rule: "kube_pod_container_resource_requests{pod%3D~'\dssp-targetp-89.*'}|resource,kube_pod_container_status_restarts_total{pod%3D~'dssp-targetp-89.*'}|container"
    prometheus.io/alert: "KubePodCrashLooping,KubeDeploymentReplicasMismatch,KubePodNotReady,KubeContainerWaiting,KubeContainerOOMKilled,KubeDeploymentRolloutStuck"
    prometheus.io/labels: "namespace=dev"
    grafana/overview-dashboard: 'http://34.29.242.32/grafana/d/ffuuiuytw0f0gb/backstage-view?var-pod_prefix=dssp-targetp-89&var-namespace=dev&kiosk' 
  tags:
    - python
    - scaffolded
spec:
  type: service
  lifecycle: Dev
  owner: user:default/chaitanya-shekhar-pandey
  system: dssp-platform
